services:
  app1:
    build: ./backend
    environment:
      - APP_NAME=app1
    expose:
      - "8080"

  app2:
    build: ./backend
    environment:
      - APP_NAME=app2
    expose:
      - "8080"

  app3:
    build: ./backend
    environment:
      - APP_NAME=app3
    expose:
      - "8080"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/files:/usr/share/nginx/html
    depends_on:
      - app1
      - app2
      - app3